<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>React + TypeScript</title>
	<link rel="stylesheet" href="<?php echo $_BASE ?>/components/bootstrap/dist/css/bootstrap.min.css">
</head>
<body>
	<div id="contenido"></div>
	<script>
		window._BASE = '<?php echo $_BASE; ?>/index.php';
	</script>
	<script src="<?php echo $_BASE ?>/components/jquery/dist/jquery.min.js"></script>
	<script src="<?php echo $_BASE ?>/components/bootstrap/dist/js/bootstrap.min.js"></script>
	<script src="<?php echo $_BASE ?>/dist/bundle.js"></script>
</body>
</html>